### ISSUE TITLE
Preserve original case class field ordering

### ISSUE THREAD

**Issue by michellemay** [andyglow/scala-jsonschema#108]
When generating schemas, it could be helpful to keep original case class field ordering. It would make tests more readable.

**Comment by vovateleport** [comment]
Hi, faced with same problem.
I have compatibility test for schema - saving generated schema to a file and checking (with diffson) saved schema vs generated in subsequent builds.
Sets in the schema (required fields, enums) are saved with different orders on project clean and compile.
I've fixed it with sorting json before storing and checking.

**Comment by michellemay** [comment]
Another option would be to replace the 'underlying' map in obj()..  Replacing that with a Seq[(String, Value)] would do it I think.

```case class obj(private val underlying: Map[String, Value]) extends Value {```

**Comment by andyglow** [comment]
@michellemay why do you think ordering should be preserved?
you said - in order to make tests more readable? but how does it help?
you can put fields in tests in corresponding order if you wish, right? 
how the fact that fields are not ordered brake it?

could you shed some more light on the issue?

**Comment by michellemay** [comment]
I'm using that generated json as both documentation and contract validation. 
Preserving the ordering in the stringified json makes it easier when manually reading/codereviewing or diffing in a PR.  Other than that, it's not really needed.  In practice, my tests read the json from disk, use ParseJson to parse it and compare it using the `obj.equals()` method (unordered on fieldSet). Having the fields ordered also makes a more predictable `required`  field name array. Otherwise, I need to run the generator to get the actual real hashmap order.

**Comment by Guillaume-iov42** [comment]
I had a similar issue, which forced me to use a different specific lib to compare json: [JSONAssert](https://github.com/skyscreamer/JSONassert)
It's a Java lib, but it's the only one I know of that has the `JSONCompareMode.NON_EXTENSIBLE` mode to compare Json objects, which means ordering in arrays is irrelevant. Two objects will be seem as equal if they have the same elements in arrays, regardless of ordering.

```
val result = JSONCompare.compareJSON(schema1AsString, schema2AsString, JSONCompareMode.NON_EXTENSIBLE)
```

**Comment by andyglow** [comment]
I am asking because if you rely on a textual representation of the schema then there are actually 2 levels at which ordering can be changed:
- `object` class representing the schema has `Set` of fields
- `obj` class that represents json object has `Map` of properties

So changing all that stuff is a little way over to me..
What am I thinking about instead, is to add an option to `JsonFormatter` that would force sorting elements before writing them out.
Would that help? What do you think?

**Comment by randuhmm** [comment]
@andyglow - It looks like the feature that was implemented supports alphabetical sorting of the properties, however, what about sorting the properties by the original order found in the case class? For example:

```
case class MyClass(
  b: Int,
  a: Int
)
```

Should produce properties where `b` comes before `a`. We have this requirement for parquet because the order matters.

**Comment by andyglow** [comment]
@randuhmm sorry for being  unavailable. had to handle a family move.
same question to you, why do you think ordering should be preserved?
