### ISSUE TITLE
ToValue changes in 0.2.2 introduces a regression

### ISSUE THREAD

**Issue by bjornbak** [andyglow/scala-jsonschema#22]
Compiling against 
```
		// json-schema generation support
		libraryDependencies += "com.github.andyglow" %% "scala-jsonschema-core" % "0.2.1",
		libraryDependencies += "com.github.andyglow" %% "scala-jsonschema-api" % "0.2.1",
		libraryDependencies += ("com.github.andyglow" %% "scala-jsonschema-circe-json" % "0.2.1")
			.excludeAll(ExclusionRule("io.circe")),
```

I can compile a schema 
```
val schemaJson: Json = Json.schema[List[PartnerConfiguration]].asCirce(Version.Draft07(id = s"http://liveintent.com/config-$version.json$timestamp"))
```

on a case class like:
```
case class PartnerConfiguration (
                                              name: String,
                                              status: DeliveryStatus,
                                              primaryKey : EncryptionKey,
                                              extraKeys : List[EncryptionKey] = List(),
                                              pairDeliveries : List[PairDelivery] = List()
)
```

But updating the dependencies to 0.2.2 to I get 
```
Can't infer a json value for extraKeys
06:36:00  [error]     val schemaJson: Json = Json.schema[List[PartnerConfiguration]].asCirce(Version.Draft07(id = s"http://liveintent.com/config-$version.json$timestamp"))
```

I can declare a custom ToValue like:
```
  implicit val encryptionKey: ToValue[EncryptionKey] = ToValue mk {
    key => Value.num(key.value.toInt)
  }
```
And then the compiler moves on to complain about pairDeliveries.

But PairDelivery is much more complex object and I feel it is a regression from 0.2.1 that I need to declare these...

Making the Lists Arrays to match https://github.com/andyglow/scala-jsonschema/compare/v0.2.1...master#diff-b0136c6356f80a307a3ef4f66f85f837R37 didn't help.

Can you fix this regression in the framework? Or can I implement a ToValue for PairDelivery that simply uses the default ToValue for the sub-objects?

**Comment by andyglow** [comment]
Hey.. yes, that's because 0.2.1 didn't have support for default values.
Now what you need to do is to bring 2 things into implicit scope:
1. your circe auto derivations
2. scala-jsonschema circe support package

so the error says it doesn't know how to make `List()` a json value because the library was designed as a thing which can give you a json-schema representation of your type, not a value.

to deal with values there are those `Support` modules. We basically delegate working with values to Play/Circe/Spray, etc...

so you should be good after
```
import io.circe.generic.auto._, io.circe.syntax._
import com.github.andyglow.jsonschema.AsCirce._
```
or whatever derivation you use, I guess

**Comment by bjornbak** [comment]
Yes it works!
Thank you!!
